class Joints:
    NUI_SKELETON_POSITION_HIP_CENTER = 0
    NUI_SKELETON_POSITION_SPINE = 1
    NUI_SKELETON_POSITION_SHOULDER_CENTER = 2
    NUI_SKELETON_POSITION_HEAD = 3
    NUI_SKELETON_POSITION_SHOULDER_LEFT = 4
    NUI_SKELETON_POSITION_ELBOW_LEFT = 5
    NUI_SKELETON_POSITION_WRIST_LEFT = 6
    NUI_SKELETON_POSITION_HAND_LEFT = 7
    NUI_SKELETON_POSITION_SHOULDER_RIGHT = 8
    NUI_SKELETON_POSITION_ELBOW_RIGHT = 9
    NUI_SKELETON_POSITION_WRIST_RIGHT = 10
    NUI_SKELETON_POSITION_HAND_RIGHT = 11
    NUI_SKELETON_POSITION_HIP_LEFT = 12
    NUI_SKELETON_POSITION_KNEE_LEFT = 13
    NUI_SKELETON_POSITION_ANKLE_LEFT = 14
    NUI_SKELETON_POSITION_FOOT_LEFT = 15
    NUI_SKELETON_POSITION_HIP_RIGHT = 16
    NUI_SKELETON_POSITION_KNEE_RIGHT = 17
    NUI_SKELETON_POSITION_ANKLE_RIGHT = 18
    NUI_SKELETON_POSITION_FOOT_RIGHT = 19

class Projections:
    ANGLE_NECK_TORSO = 1
    ANGLE_SHOULDER_ARM_R = 2
    ANGLE_SHOULDER_ARM_L = 3
    ANGLE_ARM_ARM_R = 4
    ANGLE_ARM_ARM_L = 5
    ANGLE_HIP_LEG_R = 6
    ANGLE_HIP_LEG_L = 7
    ANGLE_LEG_LEG_R = 8
    ANGLE_LEG_LEG_L = 9
    ANGLE_ARM_HIPLINE_R = 10
    ANGLE_ARM_HIPLINE_L = 11
    ANGLE_THIGH_HIPLINE_R = 12
    ANGLE_THIGH_HIPLINE_L = 13