#!/usr/bin/env python
'''
This is the entry point to the taolu enhancer platform, as is. This script has 2
utilities:
    1: Configure the error flags, and the amount of feedback the user wants,
    2: Manage the processes activation and deactivation.
To understand what the previous statements mean you may refer to the
documentation.
'''

import argparse
from core.Flags import Flags
from serial.KinectConnector import Connector
from graphics.VideoBuffer import VideoBuffer

# Process command line options and fetch user configuration
parser = argparse.ArgumentParser()
parser.parse_args()

# For the time being, assume the user wants to initiate a taolu session
conn = Connector(1)
buff = VideoBuffer(conn)
buff.loopSource()
